// src/app/screens/home/home.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  standalone: true,
  imports: [],
})
export class HomeComponent {

}

<div class="flex justify-center px-5 w-full h-full bg-main">
  <div class="px-5 py-8 mt-36 text-xl text-white bg-gray-500 rounded-lg lg:w-1/2 lg:px-20 2xl:px-48 h-min font-josefin">
    <p class="text-4xl font-bold text-center font-mmd">Bug's Plugins</p>
    <p class="mt-2 font-mono text-xs text-center">( They're called 'Bugins' )</p>
    <p class="mt-10 text-center text-emerald-300 underline">Pretty neato homepage, huh.</p>
    <p class="mt-4 text-justify">
      This website is for some of Bug1312's public plugins and add-ons, which are well known as Bugins. 
      It's a pun, Bug + Plugin = Bugin.
    </p>
  </div>
</div>

// src/screens/Home.vue
<template>
  <div class="w-full h-full bg-main flex justify-center px-5">
    <div class="mt-36 lg:w-1/2 bg-slate-900 bg-opacity-40 px-5 lg:px-20 2xl:px-48 py-8 text-white rounded-lg h-min font-josefin text-xl">
      <h2 class="font-bold font-mmd text-center">Bug's Plugins</h2>
      <h4 class="font-mono text-xs mt-2 text-center">( They're called 'Bugins' )</h4>
      <p class="mt-10 underline text-center text-emerald-300">Pretty neato homepage, huh.</p>
      <p class="text-justify mt-4">
        This website is for some of Bug1312's public Blockbench plugins, which are well known as Bugins. 
        It's a pun, Bug + Plugin = Bugin.
      </p>
    </div>
  </div>
</template>

<script>
export default {

}
</script>

<style>

</style>
